/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

public class Library {
    public static void main(String[] args) throws Exception {
//        HashTable<String> hashTable=new HashTable<String>(5);
//        hashTable.put(2,"hello");
//        System.out.println(hashTable.get(3));
//        System.out.println(hashTable.contain(7));
        System.out.println("hello from Ghaida");

    }
}
