/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

//    @Test void firstRepeatedWord() throws Exception{
//        HashTable hashMap= new HashTable(7);
//        assertEquals("hope,", hashMap.repeatedWord("It was the bestof foolishness, spring of hope,"));
//
//}
}
