/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test public void addVertex(){

        Graph graph = new Graph();

        graph.addVertex("Ghaida");
        graph.addVertex("Gharaibeh");

        assertNotNull(graph.getVertices());
        assertEquals(2,graph.size());
    }

    @Test public void addEdge(){

        Graph graph = new Graph();

        graph.addVertex("Ghaida");
        graph.addVertex("Rahmeh");
        graph.addEdge("Ghaida", "Rahmeh");

        assertEquals("Vertex{label='Rahmeh'}[Vertex{label='Ghaida'}]Vertex{label='Ghaida'}[Vertex{label='Rahmeh'}]", graph.printGraph());
    }

    @Test public void vertexNeighbors(){

        Graph graph = new Graph();

        graph.addVertex("Ghaida");
        graph.addVertex("Rhmeh");
        graph.addVertex("Moh");
        graph.addVertex("Saif");
        graph.addEdge("Ghaida", "Moh");
        graph.addEdge("Ghaida", "Rahmeh");
        graph.addEdge("Saif", "Rahmeh");

        assertEquals("[Vertex{label='Alaa'}, Vertex{label='Mariam'}]",graph.getNeighbors("Doaa").toString());
        assertEquals("[Vertex{label='Mariam'}]", graph.getNeighbors("Amara").toString());

    }


}
