/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphs;

public class Library {
    public static void main(String[] args) {

        Graph graph = new Graph();

        graph.addVertex("Ghaida");
        graph.addVertex("Rahmeh");
        graph.addVertex("Mariam");
        graph.addVertex("Alaa");

        graph.addEdge("Ghaida","Amara");
        graph.addEdge("Ghaida", "Mariam");
        graph.addEdge("Ghaida", "Rahmeh");
        graph.addEdge("Amara","Mariam");
        graph.addEdge("Mariam","Rahmeh");
        graph.addEdge("Rahmeh", "Amara");

        System.out.println(graph.printGraph());


        System.out.println();
        System.out.println(graph.getVertices());

        System.out.println();
        System.out.println(graph.getNeighbors("Amara"));

        System.out.println();
        System.out.println(graph.size());

    }
}
