/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTableDataStructure;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void test(){

        HashTable<String, Integer> clubs = new HashTable<String, Integer>();

        assertTrue(clubs.isEmpty());

        clubs.add("Real Madrid",100);
        assertEquals(1,clubs.getSize());

        clubs.add("Barcelona", 200);
        assertEquals(2,clubs.getSize());
        assertFalse(clubs.isEmpty());

        clubs.remove("Barcelona");
        assertEquals(1,clubs.getSize());

        assertTrue(clubs.contains("Real Madrid"));
        assertFalse(clubs.contains("Man United"));

        clubs.remove("Real Madrid");
        assertTrue(clubs.isEmpty());
    }
}

