/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test void ReverseInsertionSort() {

        int[] ReverseSortedArr = {20, 18, 12, 8, 5, -2};
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(Library.insertionSort(ReverseSortedArr)));
    }
    @Test void FewUniquesInsertionSort() {
        int[] FewUniquesArr = {5, 12, 7, 5, 5, 7};
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(Library.insertionSort(FewUniquesArr)));
    }
    @Test void NearlyInsertionSort() {
        int[]  NearlySortedArr = {2,3,5,7,13,11};
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(Library.insertionSort(NearlySortedArr)));
    }
}
