/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class Library {
    public static void main(String[] args) {

        Graph graph = new Graph();

        graph.addVertex("Doaa");
        graph.addVertex("Amara");
        graph.addVertex("Mariam");
        graph.addVertex("Alaa");

        graph.addEdge("Ghaida","Gharaibeh");
        graph.addEdge("Doaa", "Mariam");
        graph.addEdge("Doaa", "Alaa");
        graph.addEdge("Amara","Mariam");
        graph.addEdge("Mariam","Alaa");
        graph.addEdge("Alaa", "Amara");

        System.out.println(graph.printGraph());


        System.out.println();
        System.out.println(graph.getVertices());

        System.out.println();
        System.out.println(graph.getNeighbors("Amara"));

        System.out.println();
        System.out.println(graph.size());

    }
}
